version: "3.3"
services:
  iris:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 32782:1972
      - 32783:52773
      - 32784:53773
    volumes:
      - ./fhirUI:/usr/irissys/csp/user/fhirUI
      - ~/iris.key:/usr/irissys/mgr/iris.key
      - ./:/irisdev/app
